# Site settings
title: "Karfield's Coding Tips"
email: ""
description: > # this means to ignore newlines until "baseurl:"
    This is my shares of coding stuff, Thanks for your visiting!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://open.karfield.com" # the base hostname & protocol for your site
twitter_username: ""
github_username:  karfield

# Build settings
#markdown: kramdown
markdown: redcarpet
