# Site settings
title: "Karfield's Shares on Coding"
email: ""
description: > # this means to ignore newlines until "baseurl:"
    This is my shares of tips and opinions on coding stuff, Thx your visiting!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://open.karfield.com" # the base hostname & protocol for your site
twitter_username: ""
github_username:  karfield

# Build settings
markdown: kramdown

